name: Publish
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  run-tests:
    name: Run tests
    permissions:
      contents: write
    uses: ./.github/workflows/test.yaml

  check-linting:
    name: Check linting
    permissions:
      contents: read
    uses: ./.github/workflows/lint.yml

  publish:
    runs-on: ubuntu-latest
    needs: [run-tests, check-linting]

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
